name: 02 - Workflow Events

on: push

jobs:
    echo-one:
        runs-on: ubuntu-latest
        steps:
        - name: Say the trigger event
          run: echo "This workflow was triggered by a push event."
