name: 13 - Using caching

on:
    workflow_dispatch:
        inputs:
            use-cache:
                type: boolean
                default: true
                description: Whether to execute cache step
            node-version:
                type: choice
                options:
                    - '24.x'
                    - '26.x'
                default: '24.x'
                description: Node version

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: 13-caching/template
        
        steps:
            - name: Checkout Code
              uses: actions/checkout@v7

            - name: Setup Node
              uses: actions/setup-node@v6
              with:
                node-version: ${{ inputs.node-version }}

            - name: Download cached dependencies
              if: ${{ inputs.use-cache }}
              uses: actions/cache@v6
              id: cache
              with:
                path: 13-caching/template/node_modules
                key: deps-node-modules-${{ hashFiles('13-caching/template/package-lock.json') }}
            
            - name: Install dependencies
              if: ${{ steps.cache.outputs.cache-hit == 'true' }}
              run: npm ci

            - name: Testing
              run: npm run build

            - name: Deploying to nonprod
              run: echo "Deploying to nonprod"