name: 15 - Working with matrices

on:
    workflow_dispatch:

jobs:
    backwards-compatibility:
        name: ${{ matrix.os }}-${{ matrix.node-versions }}
        strategy:
            matrix:
                node-versions: [24.x, 26.x]
                os:
                    - ubuntu-latest
                    - windows-latest
        runs-on: ${{ matrix.os }}

        steps:
            - name: Setup Node
              uses: actions/setup-node@v6
              with:
                node-version: ${{ matrix.node-versions }}

            - name: Perform some tests
              run: echo "Running tests on OS ${{ matrix.os }} and NodeJS ${{ matrix.node-versions }}"