name: 20 - Workflow security

on:
    pull_request:

jobs:
    safer-pr:
        runs-on: ubuntu-latest
        steps:
            - name:
              uses: actions/checkout@v7
            - name: Check PR title
              env:
                TITLE: ${{ github.event.pull_request.title }}
              run: |
                if [[ $TITLE =~ ^feat ]]; then
                echo "PR is a feature"
                exit 0
                else
                echo "PR is not a feature"
                exit 1
                fi